spring:
  application:
    name: xgm
  # ğŸ‘‡ å¼€å‘æ—¶ä¸´æ—¶è®¾ä¸º devï¼Œæäº¤ä»£ç å‰ç¡®è®¤ï¼
  profiles:
    active: dev   # é»˜è®¤æ¿€æ´» dev ç¯å¢ƒï¼ˆæœ¬åœ°å¼€å‘ç”¨ï¼‰


logging:
  file:
    name: logs/app.log        # æ—¥å¿—æ–‡ä»¶è·¯å¾„
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#   ç›´æ¥å†™logback.xmlä¹Ÿæ˜¯å¯ä»¥çš„ï¼Œå±äºç‰¹æ®Šé…ç½®
